EC-Ecom2/Models/Checkout/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EC_Ecom2.Models.Checkout
{
    public class Cart
    {
        public int Id { get; set; }

        
        public double Total { get; set; }
        public string State { get; set; } // Can be "active", "ordered", "abandoned"

        public string SessionId { get; set; }

        public string UserId { get; set; }
        //public ApplicationUser User { get; set; }

        public virtual ICollection<Cartitem> Cartitems { get; set; }
    }
}

EC-Ecom2/Models/Checkout/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EC_Ecom2.Models.Checkout
{
    public class CartViewModel
    {
        public int Id { get; set; }
        public Cart Cart { get; set; }
        public virtual ICollection<Cartitem> Cartitems { get; set; }
    }
}

EC-Ecom2/ViewModels/Checkout/CheckoutDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EC_Ecom2.Models;
using EC_Ecom2.Models.Checkout;
using EC_Ecom2.Models.Users;

namespace EC_Ecom2.ViewModels.Checkout
{
    public class CheckoutDetailsViewModel
    {
        public int Id { get; set; }

        public int CartId { get; set; }
        public virtual Cart Cart { get; set; }

        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }

        public int UserProfileId { get; set; }
        public virtual UserProfile UserProfile { get; set; }

        public double ShippingCost { get; set; }
    }
}

EC-Ecom2/Controllers/Checkout/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EC_Ecom2.Models;
using EC_Ecom2.Models.App;
using EC_Ecom2.Models.Checkout;
using EC_Ecom2.ViewModels.Checkout;
using Microsoft.AspNet.Identity;

namespace EC_Ecom2.Controllers.Checkout
{
    public class CartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Carts
        //public ActionResult Index()
        //{
        //    return View(db.Carts.ToList());
        //}
        public ActionResult Index()
        {
            var cartViewModel = new CartViewModel();
            //ICollection<Cartitem> cartItemList;
            Cart cart = new Cart();
            //const string CartSessionKey = "CartId";
            string sessionId = System.Web.HttpContext.Current.Session.SessionID;
            var existingCart = from c in db.Carts
                               where c.SessionId == sessionId && c.State == "active"
                               select c;

            var cartItems = from c in db.Cartitems
                            //where c.Cart.Id == cart.Id
                            where c.Cart.Id == existingCart.FirstOrDefault().Id
                            select c;
            //foreach ( var item in cartItems)
            //{   
            //    System.Diagnostics.Debug.WriteLine("Product id: " + item.ProductId );
            //}
            
            foreach(var item in existingCart)
            {
                cart = item;
            }
            cartViewModel.Cart = cart;
            cartViewModel.Cartitems = cartItems.ToList();

            return View("CartIndex", cartViewModel);
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Total,State,SessionId,UserId")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Total,State,SessionId,UserId")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Handles cart.
        // Handles both updating of cart and placing of order.
        //public ActionResult HandleCart(int CartId, int CartitemId, int newQuantity)
        public ActionResult HandleCart(string submitButton, string returnUrl)
        {
            //System.Diagnostics.Debug.WriteLine("Inside HandleCart.");
            string cartId = Request.Form["item.Cart.Id"];
            //System.Diagnostics.Debug.WriteLine("CartId is: " + cartId[0]);
            //System.Diagnostics.Debug.WriteLine("CartId2 is: " + Request.Form["item.Cart.Id"]);

            var cartItemIds = Request.Form["item.Id"];
            var cartItemIdsArray = cartItemIds.Split(',');
            System.Diagnostics.Debug.WriteLine("Number of cartitemids is: " + cartItemIdsArray.Length);
            System.Diagnostics.Debug.WriteLine("First cartitemids is: " + cartItemIdsArray[0]);

            var productIds = Request.Form["item.Product.Id"];
            var productIdsArray = productIds.Split(',');
            System.Diagnostics.Debug.WriteLine("Number of productids is: " + productIdsArray.Length);

            var quantities = Request.Form["item.Quantity"];
            var quantitiesArray = quantities.Split(',');
            System.Diagnostics.Debug.WriteLine("Number of productids is: " + quantitiesArray.Length);

            // You will have to get product price somehow.
            System.Diagnostics.Debug.WriteLine("Quantity is: " + Request.Form["item.Quantity"][0]);

            switch (submitButton)
            {
                case "Uppdatera":
                    // Update the quantity and price for each cartitem                    
                    //System.Diagnostics.Debug.WriteLine("Klicked button: Uppdatera");
                    // The number of cartitem IDs is the same as there are cartitems in 
                    // the cart.
                    double cartTotal = 0;
                    for (int i = 0; i < cartItemIdsArray.Length; i++)
                    {
                        //System.Diagnostics.Debug.WriteLine("i is: " + i);
                        string counter = cartItemIdsArray[i].ToString();
                        //System.Diagnostics.Debug.WriteLine("counter is: " + counter);
                        int j = Convert.ToInt32(counter);
                        var cartItem = db.Cartitems.Find( j );
                        double productPrice = db.Products.Find(Int32.Parse(productIdsArray[i].ToString())).Price;
                        // If the number in the input field is 0 the cartitem will be removed.
                        if (Int32.Parse(quantitiesArray[i].ToString()) < 1)
                        {
                            db.Cartitems.Remove(cartItem);
                        }
                        else
                        {
                            cartItem.Quantity = Int32.Parse(quantitiesArray[i].ToString());
                            cartItem.CartitemTotal = Int32.Parse(quantitiesArray[i].ToString()) * db.Products.Find(Int32.Parse(productIdsArray[i].ToString())).Price;
                            cartTotal += cartItem.CartitemTotal;
                        }
                        
                        db.SaveChanges();
                    }
                    string sId = System.Web.HttpContext.Current.Session.SessionID;
                    var cartFromDb = from c in db.Carts
                                     where c.SessionId == sId && c.State == "active"
                                     select c;
                    var cartForTotal = cartFromDb.FirstOrDefault();
                    cartForTotal.Total = cartTotal;
                    db.SaveChanges();

                    ///////////////////////////////////////////////////////
                    // Getting the entire cart and redirecting to cartindex
                    ///////////////////////////////////////////////////////
                    var cartViewModel = new CartViewModel();
                    Cart cart = new Cart();
                    string sessionId = System.Web.HttpContext.Current.Session.SessionID;
                    var existingCart = from c in db.Carts
                                       where c.SessionId == sessionId && c.State == "active"
                                       select c;

                    var cartItems = from c in db.Cartitems
                                        //where c.Cart.Id == cart.Id
                                    where c.Cart.Id == existingCart.FirstOrDefault().Id
                                    select c;

                    foreach (var item in existingCart)
                    {
                        cart = item;
                    }
                    cartViewModel.Cart = cart;
                    cartViewModel.Cartitems = cartItems.ToList();
                    return View("CartIndex", cartViewModel);
                // Getting the entire cart and redirecting to cartindex ends here
                case "Checkoutdetaljer":

                    return RedirectToAction("CheckoutDetails");

                case "Lägg order":

EC-Ecom2/Views/Carts/CartIndex.cshtml
@model EC_Ecom2.Models.Checkout.CartViewModel

@{
  ViewBag.Title = "Index";
}

<h2>Din varukorg</h2>

<p>
  @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Cart.Total)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Cart.State)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Cart.SessionId)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Cart.UserId)
    </th>
    @*<th></th>*@
  </tr>

  @*@foreach (var item in Model.Cart)
    {*@
  <tr>
    <td>
      @Html.DisplayFor(modelItem => Model.Cart.Total)
    </td>
    <td>
      @Html.DisplayFor(modelItem => Model.Cart.State)
    </td>
    <td>
      @Html.DisplayFor(modelItem => Model.Cart.SessionId)
    </td>
    <td>
      @Html.DisplayFor(modelItem => Model.Cart.UserId)
    </td>
    @*<td>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Cart.Id }) |
        @Html.ActionLink("Details", "Details", new { id = Model.Cart.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.Cart.Id })
      </td>*@
  </tr>
  @*}*@

</table>

<h3>Dina varor</h3>
@using (Html.BeginForm("HandleCart", "Carts", FormMethod.Post, new { id = "cartform", name = "cartform" }))
{
  @Html.AntiForgeryToken()


  foreach (var item in Model.Cartitems)
  {
<div>
  @Html.HiddenFor(modelItem => item.Product.Id)
  @Html.HiddenFor(modelItem => item.Cart.Id)
  @Html.HiddenFor(modelItem => item.Id)

  <span>Produktid: </span>@Html.DisplayFor(modelItem => item.Product.Id)

  <span>Produktnamn: </span>@Html.DisplayFor(modelItem => item.Product.Name)
  <span>Totalt för den här varan: </span>@Html.DisplayFor(modelItem => item.CartitemTotal)

  <span>Antal: </span>@Html.EditorFor(modelItem => item.Quantity,
    new
    {
      htmlAttributes = new
      {
        @class = "form-control",
        @id = item.Product.Id,
        @cartId = item.Cart.Id,
        @cartitemId = item.Id,
        @name = "quantity"
      }
    })
  
    </div>
    <div>*********************************************************</div>
  }
  <input type="submit" name="submitButton" value="Uppdatera"  
         @{ if(!Model.Cartitems.Any()) { 
             @:disabled="disabled" 
        } }
         /><br />

  <input type="submit" name="submitButton" value="Checkoutdetaljer"  
         @{ if(!Model.Cartitems.Any()) { 
             @:disabled="disabled" 
        } }
         /><br />
}

EC-Ecom2/Views/Carts/CheckoutDetails.cshtml
@model EC_Ecom2.ViewModels.Checkout.CheckoutDetailsViewModel

@{
  ViewBag.Title = "CheckoutDetails";
}

<h2>CheckoutDetails</h2>

<div>Cart total is: @Model.Cart.Total</div>
<div>Frakt tillkommer: @Model.ShippingCost</div>

@foreach (var item in Model.Cart.Cartitems)
{
  @Html.HiddenFor(modelItem => item.Product.Id)

  @Html.HiddenFor(modelItem => item.Cart.Id)
  @Html.HiddenFor(modelItem => item.Id)

  <div>Product id: @Html.DisplayFor(modelItem => item.Product.Id)</div>
  <div>Quantity: @Html.DisplayFor(modelItem => item.Quantity)</div>

  <div>Product name: @Html.DisplayFor(modelItem => item.Product.Name)</div>
  <span>Cartitem total: </span>@Html.DisplayFor(modelItem => item.CartitemTotal)
    <div>-------------------------</div>
}

@using (Html.BeginForm("Payment", "Carts", FormMethod.Post, new { id = "checkout-details", name = "checkout-details" }))
{
  @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>Dubbelkolla dina uppgifter</h4>
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      @Html.HiddenFor(model => model.Id)

      @*<div class="form-group">
      @Html.LabelFor(model => model.CartId, "CartId", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownList("CartId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CartId, "", new { @class = "text-danger" })
      </div>
    </div>*@

      <div class="form-group">
        @Html.LabelFor(model => model.ApplicationUser.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.ApplicationUser.Email)
          @Html.ValidationMessageFor(model => Model.ApplicationUser.Email, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.ApplicationUser.UserName, "UserName", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.ApplicationUser.UserName)
          @Html.ValidationMessageFor(model => Model.ApplicationUser.UserName, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Firstname, "Firstname", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Firstname)
          @Html.ValidationMessageFor(model => Model.UserProfile.Firstname, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Middlename, "Middlename", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Middlename)
          @Html.ValidationMessageFor(model => Model.UserProfile.Middlename, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Lastname, "Lastname", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Lastname)
          @Html.ValidationMessageFor(model => Model.UserProfile.Lastname, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Streetaddress, "Streetaddress", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Streetaddress)
          @Html.ValidationMessageFor(model => Model.UserProfile.Streetaddress, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Postalcode, "Postalcode", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Postalcode)
          @Html.ValidationMessageFor(model => Model.UserProfile.Postalcode, "", new { @class = "text-danger" })
        </div>
      </div>
      
      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.Phonenumber, "Phonenumber", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.Phonenumber)
          @Html.ValidationMessageFor(model => Model.UserProfile.Phonenumber, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfile.City, "City", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(modelItem => Model.UserProfile.City)
          @Html.ValidationMessageFor(model => Model.UserProfile.City, "", new { @class = "text-danger" })
        </div>
      </div>

      @*<div class="form-group">
      @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.UserProfileId, "UserProfileId", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownList("UserProfileId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.UserProfileId, "", new { @class = "text-danger" })
      </div>
    </div>*@

      <div>Om det här stämmer fortsätt till betalning</div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Till betalning" class="btn btn-default" />
        </div>
      </div>
    </div>
}

<div>
  @Html.ActionLink("Tillbaka till varukorgen", "Index")
</div>

EC-Ecom2/Views/Carts/Create.cshtml
@model EC_Ecom2.Models.Checkout.Cart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SessionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SessionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EC-Ecom2/Views/Carts/Payment.cshtml
@model EC_Ecom2.ViewModels.Checkout.CheckoutDetailsViewModel

@{
  ViewBag.Title = "CheckoutDetails";
}

<h2>Betalning</h2>

<h3>Summa att betala: @Model.Cart.Total</h3>
<h3>Frakt tillkommer: @Model.ShippingCost</h3>

@foreach (var item in Model.Cart.Cartitems)
{
  @Html.HiddenFor(modelItem => item.Product.Id)

  @Html.HiddenFor(modelItem => item.Cart.Id)
  @Html.HiddenFor(modelItem => item.Id)

  <div>Product id: @Html.DisplayFor(modelItem => item.Product.Id)</div>
  <div>Quantity: @Html.DisplayFor(modelItem => item.Quantity)</div>

  <div>Product name: @Html.DisplayFor(modelItem => item.Product.Name)</div>
  <span>Cartitem total: </span>@Html.DisplayFor(modelItem => item.CartitemTotal)
  <div>-------------------------</div>
}
  <h3>Dina uppgifter</h3>
<div>Förnamn: @Html.DisplayFor(modelItem => Model.UserProfile.Firstname)</div>
<div>Mellannamn: @Html.DisplayFor(modelItem => Model.UserProfile.Middlename)</div>
<div>Efternamn: @Html.DisplayFor(modelItem => Model.UserProfile.Lastname)</div>
<div>Gata: @Html.DisplayFor(modelItem => Model.UserProfile.Streetaddress)</div>
<div>Postnummer: @Html.DisplayFor(modelItem => Model.UserProfile.Postalcode)</div>
<div>Stad: @Html.DisplayFor(modelItem => Model.UserProfile.City)</div>
<div>Telefon: @Html.DisplayFor(modelItem => Model.UserProfile.Phonenumber)</div>
@using (Html.BeginForm("PlaceOrder", "Carts", FormMethod.Post, new { id = "checkout-details", name = "checkout-details" }))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Betalningsalternativ</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @*<div class="form-group">
        @Html.LabelFor(model => model.CartId, "CartId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownList("CartId", null, htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.CartId, "", new { @class = "text-danger" })
        </div>
      </div>*@

    @*<div class="form-group">
      @Html.LabelFor(model => model.ApplicationUser.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(modelItem => Model.ApplicationUser.Email)
        @Html.ValidationMessageFor(model => Model.ApplicationUser.Email, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.UserProfile.City, "City", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(modelItem => Model.UserProfile.City)
        @Html.ValidationMessageFor(model => Model.UserProfile.City, "", new { @class = "text-danger" })
      </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.UserProfileId, "UserProfileId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownList("UserProfileId", null, htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.UserProfileId, "", new { @class = "text-danger" })
        </div>
      </div>*@

    <div>Hur vill du betala?</div>


    "Vid leverans", "Check", "Kort", "Paypal"
    @{
      List<SelectListItem> listItems = new List<SelectListItem>();
      listItems.Add(new SelectListItem
      {
        Text = "Vid leverans",
        Value = "Vid leverans"
      });
      listItems.Add(new SelectListItem
      {
        Text = "Check",
        Value = "Check",
        Selected = true
      });
      listItems.Add(new SelectListItem
      {
        Text = "Kort",
        Value = "Kort"
      });
      listItems.Add(new SelectListItem
      {
        Text = "Paypal",
        Value = "Paypal"
      });
    }

    @Html.DropDownList("Payment", listItems, "-- Select Status --")



    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Lägg order" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Tillbaka till varukorgen", "Index")
</div>